name: Build and deploy Node.js app to Azure Web App - nadaviesportal
 
on:
  push:
    branches:
      - master
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
 
    steps:
      - uses: actions/checkout@v4
 
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
 
      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present
          
      - name: Move dist content to root for deployment
        run: |
          # Copy all files from dist to root, preserving dist folder for reference
          cp -r dist/* .
          
          # Create a basic web.config for static file hosting
          echo '<?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <rewrite>
                <rules>
                  <rule name="SPA">
                    <match url=".*" />
                    <conditions logicalGrouping="MatchAll">
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="index.html" />
                  </rule>
                </rules>
              </rewrite>
            </system.webServer>
          </configuration>' > web.config
          
          # Update package.json to include a serve command if using Node.js
          if grep -q "\"scripts\"" package.json; then
            # Add a static serve command if not already present
            if ! grep -q "\"start\"" package.json; then
              sed -i 's/"scripts": {/"scripts": {\n    "start": "serve -s .\/",/' package.json
              npm install --save serve
            fi
          fi
          
          # List files for verification
          echo "Files in deployment root:"
          ls -la

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
 
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
 
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
 
      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C24AD94F6C07499E8859287A9BEF335B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7E81C685276E4CFAAB5CEA5BE67CD301 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BAF603802EB94003ABFADF1BDE6AD518 }}
 
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nadaviesportal'
          slot-name: 'Production'
          package: .
