name: Build and deploy Vite app to Azure Web App
 
on:
  push:
    branches:
      - master
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout
 
    steps:
      - uses: actions/checkout@v4
 
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
 
      - name: npm install and build
        run: |
          npm install
          npm run build
 
      - name: Prepare deployment package
        run: |
          # Create a deployment directory with just the dist contents
          mkdir deployment
          cp -r dist/* deployment/
          # Add a web.config file for proper routing
          echo '<?xml version="1.0" encoding="utf-8"?>
            <configuration>
              <system.webServer>
                <rewrite>
                  <rules>
                    <rule name="SPA Routes" stopProcessing="true">
                      <match url=".*" />
                        <conditions logicalGrouping="MatchAll">
                          <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                            <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                            </conditions>
                            <action type="Rewrite" url="/" />
                          </rule>
                        </rules>
                      </rewrite>
                    <staticContent>
                  <mimeMap fileExtension=".webmanifest" mimeType="application/manifest+json" />
                </staticContent>
              </system.webServer>
            </configuration>' > deployment/web.config
      - name: Zip deployment package
        run: cd deployment && zip -r ../release.zip ./*
 
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: vite-app
          path: release.zip
 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: vite-app
 
      - name: Unzip artifact for deployment
        run: unzip release.zip -d deployment
 
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nadaviesportal'
          slot-name: 'Production'
          package: ./deployment
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_aae083634e2d48a0b73d8ead6a7f7012 }}
