name: Build and deploy Node.js app to Azure Web App - nadaviesportal
 
on:
  push:
    branches:
      - master
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
 
    steps:
      - uses: actions/checkout@v4
 
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
 
      - name: npm install and build
        run: |
          npm install
          npm run build
          
      - name: Create server files for Azure
        run: |
          # Create a simple express server
          echo 'const express = require("express");
          const path = require("path");
          
          const app = express();
          const PORT = process.env.PORT || 8080;
          
          // Serve static files from the dist directory
          app.use(express.static(path.join(__dirname, "dist")));
          
          // For any request that doesn't match a static file, send the index.html
          app.get("*", (req, res) => {
            res.sendFile(path.join(__dirname, "dist", "index.html"));
          });
          
          app.listen(PORT, () => {
            console.log(`Server running on port ${PORT}`);
          });' > server.js
          
          # Update package.json for Azure
          echo '{
            "name": "vite-app",
            "version": "1.0.0",
            "scripts": {
              "start": "node server.js"
            },
            "dependencies": {
              "express": "^4.18.2"
            }
          }' > package.json
          
          # Install express for the server
          npm install express

      - name: Zip files for deployment
        run: zip -r release.zip server.js package.json package-lock.json dist node_modules
 
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
 
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
 
      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C24AD94F6C07499E8859287A9BEF335B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7E81C685276E4CFAAB5CEA5BE67CD301 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BAF603802EB94003ABFADF1BDE6AD518 }}
 
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nadaviesportal'
          slot-name: 'Production'
          package: .
