name: Build and deploy Node.js app to Azure Web App - nadaviesportal
 
on:
  push:
    branches:
      - master
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
 
    steps:
      - uses: actions/checkout@v4
 
      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
 
      - name: npm install and build
        run: |
          npm install
          npm run build --if-present
 
      - name: Prepare for deployment
        run: |
          # Copy dist files directly to root for deployment
          mkdir -p deploy_package
          cp -r dist/* deploy_package/
          
          # Create web.config in the root
          echo '<?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <rewrite>
                <rules>
                  <rule name="SPA">
                    <match url=".*" />
                    <conditions logicalGrouping="MatchAll">
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="index.html" />
                  </rule>
                </rules>
              </rewrite>
            </system.webServer>
          </configuration>' > deploy_package/web.config
 
      - name: Zip artifact for deployment
        run: cd deploy_package && zip -r ../release.zip ./*
 
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip
 
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
 
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
 
      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C24AD94F6C07499E8859287A9BEF335B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_7E81C685276E4CFAAB5CEA5BE67CD301 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BAF603802EB94003ABFADF1BDE6AD518 }}
 
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nadaviesportal'
          slot-name: 'Production'
          package: .
